### ISSUE TITLE
Can't run for Combine.framework not loaded

### ISSUE THREAD

**Issue by calvingit** [Moya/Moya#1927] opened 2019-09-28 09:49 UTC
Xcode: 11.0
Swift: 5
Carthage: 0.33.0
Moya: 14.0.0-beta.3
iOS: 12.4.2

Error:

> dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Combine
  Referenced from: /private/var/containers/Bundle/Application/EE36155E-CDB8-46F2-9A2E-DA7B7DACF603/SmartHome.app/Frameworks/Moya.framework/Moya
  Reason: image not found

It's OK when I use Xcode 10.0 and Moya 14.0.0-alpha.2

**Comment by sunshinejr** [comment] 2019-09-28 11:40
Hey @calvingit, thanks for reporting the issue. We thought it was fixed in beta.3 but we will have to revise the fix for that.

**Comment by sunshinejr** [comment] 2019-09-29 12:56
Hmm, was trying to reproduce it but I wasn't able to do so. Can you check please otool your framework and post here the output? E.g. when you finish carthage bootstrap/update, run this command: `otool -l Carthage/Build/iOS/Moya.framework/Moya`.

If anyone else is experiencing the same issue please post your detailed environment. Thanks!

**Comment by calvingit** [comment] 2019-09-30 01:07
The otool output is:

```bash
Carthage/Build/iOS/Moya.framework/Moya:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    27       3792 0x02100085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 1432
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x000000000002a000
  fileoff 0
 filesize 172032
  maxprot 0x00000005
 initprot 0x00000005
   nsects 17
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000000000014e0
      size 0x0000000000022910
    offset 5344
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000000023df0
      size 0x00000000000005e2
    offset 146928
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x00000000000243d4
      size 0x00000000000009de
    offset 148436
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x0000000000024dc0
      size 0x000000000000196f
    offset 150976
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_typeref
   segname __TEXT
      addr 0x0000000000026730
      size 0x0000000000000f39
    offset 157488
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_capture
   segname __TEXT
      addr 0x000000000002766c
      size 0x00000000000004f4
    offset 161388
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_reflstr
   segname __TEXT
      addr 0x0000000000027b60
      size 0x000000000000052b
    offset 162656
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_fieldmd
   segname __TEXT
      addr 0x000000000002808c
      size 0x0000000000000698
    offset 163980
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_proto
   segname __TEXT
      addr 0x0000000000028724
      size 0x00000000000000ac
    offset 165668
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_types
   segname __TEXT
      addr 0x00000000000287d0
      size 0x000000000000007c
    offset 165840
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x0000000000028850
      size 0x00000000000007f0
    offset 165968
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __swift5_protos
   segname __TEXT
      addr 0x0000000000029040
      size 0x000000000000001c
    offset 168000
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_builtin
   segname __TEXT
      addr 0x000000000002905c
      size 0x0000000000000028
    offset 168028
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_methname
   segname __TEXT
      addr 0x0000000000029084
      size 0x000000000000013e
    offset 168068
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __swift5_assocty
   segname __TEXT
      addr 0x00000000000291c4
      size 0x0000000000000098
    offset 168388
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000000002925c
      size 0x00000000000008e8
    offset 168540
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x0000000000029b48
      size 0x00000000000004b0
    offset 170824
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 1112
  segname __DATA
   vmaddr 0x000000000002a000
   vmsize 0x0000000000005000
  fileoff 172032
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 13
    flags 0x0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x000000000002a000
      size 0x0000000000000008
    offset 172032
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 251 (index into indirect symbol table)
 reserved2 0
Section
  sectname __got
   segname __DATA
      addr 0x000000000002a008
      size 0x00000000000004c0
    offset 172040
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 252 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x000000000002a4c8
      size 0x00000000000007d8
    offset 173256
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 404 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x000000000002aca0
      size 0x00000000000013d8
    offset 175264
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_classlist
   segname __DATA
      addr 0x000000000002c078
      size 0x0000000000000048
    offset 180344
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_imageinfo
   segname __DATA
      addr 0x000000000002c0c0
      size 0x0000000000000008
    offset 180416
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_const
   segname __DATA
      addr 0x000000000002c0c8
      size 0x0000000000000940
    offset 180424
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_selrefs
   segname __DATA
      addr 0x000000000002ca08
      size 0x0000000000000088
    offset 182792
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000005
 reserved1 0
 reserved2 0
Section
  sectname __objc_classrefs
   segname __DATA
      addr 0x000000000002ca90
      size 0x0000000000000048
    offset 182928
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000000002cad8
      size 0x0000000000000ea5
    offset 183000
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift_hooks
   segname __DATA
      addr 0x000000000002d980
      size 0x00000000000000b8
    offset 186752
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x000000000002da40
      size 0x0000000000000e18
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x000000000002e858
      size 0x0000000000000018
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x000000000002f000
   vmsize 0x000000000005a000
  fileoff 188416
 filesize 367888
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 56
         name @rpath/Moya.framework/Moya (offset 24)
   time stamp 1 Thu Jan  1 08:00:01 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 188416
    rebase_size 456
       bind_off 188872
      bind_size 6216
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 195088
 lazy_bind_size 13864
     export_off 208952
    export_size 11944
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 222120
   nsyms 5910
  stroff 319300
 strsize 211784
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 5108
     iextdefsym 5108
     nextdefsym 394
      iundefsym 5502
      nundefsym 408
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 316680
  nindirectsyms 655
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 06092938-407E-3125-B0FC-219A16936227
Load command 8
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 10.0
      sdk 13.0
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_WEAK_DYLIB
      cmdsize 80
         name /System/Library/Frameworks/Combine.framework/Combine (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 128.10.0
compatibility version 0.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/Foundation.framework/Foundation (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1665.15.0
compatibility version 300.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libobjc.A.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 228.0.0
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1281.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1665.15.0
compatibility version 150.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /System/Library/Frameworks/UIKit.framework/UIKit (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 61000.0.0
compatibility version 1.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/Alamofire.framework/Alamofire (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftCore.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1100.2.255
compatibility version 1.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftDispatch.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 0.0.0
compatibility version 1.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftFoundation.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 0.0.0
compatibility version 1.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftObjectiveC.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 0.0.0
compatibility version 1.0.0
Load command 21
          cmd LC_RPATH
      cmdsize 32
         path /usr/lib/swift (offset 12)
Load command 22
          cmd LC_RPATH
      cmdsize 48
         path @executable_path/../Frameworks (offset 12)
Load command 23
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 24
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 220896
 datasize 1096
Load command 25
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 221992
 datasize 128
Load command 26
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 531088
 datasize 25216
```

**Comment by phimage** [comment] 2019-09-30 08:05
Hi, same issue with a command line tool on macOS 10.14(so without `Combine`) with Xcode 11
and release mode (with debug no problem)

```
$ swift build -c release
...
$ <path>/.build/x86_64-apple-macosx/release/myexecutable
dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
  Referenced from: <path>/.build/x86_64-apple-macosx/release/myexecutable
  Reason: image not found
Abort trap: 6
```

exemple of Package.swift
```swift
// swift-tools-version:5.0
import PackageDescription

let package = Package(
    name: "MyExecutable",
    platforms: [
        .macOS(.v10_14)
    ],
    products: [
        .executable(
            name: "myexecutable", targets: ["MyExecutable"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Moya/Moya.git" , .revision("14.0.0-beta.3"))
    ],
    targets: [
        .target(
            name: "MyExecutable",
            dependencies: ["Moya"],
            path: "Sources/"
        )
    ]
)
```

**Comment by sunshinejr** [comment] 2019-09-30 15:04
Hey @phimage - thanks a lot for your input as well. Can you do me a favor and also `otool` your executables - both in debug and release?

@calvingit are you sure you are using the framework you otooled in your app? I was able to successfully run weak-linked Combine frameworks on both iOS 12.* device and also lower simulators... I'm not sure what could be the issue with Carthage now.

**Comment by phimage** [comment] 2019-09-30 15:18
sample projet with inside release.otool and debug.otool 
https://github.com/phimage/moyacmdtest

**Comment by sunshinejr** [comment] 2019-09-30 15:29
@phimage awesome, thanks a lot! It seems like SPM doesn't weak-link Combine in release mode... Not sure why yet, but it might be similar for CocoaPods. Still not sure why weak-linked library would crash with Carthage as well. This is all very confusing... I don't want to roll back those Combine extensions but it might be the only solution if we don't find out why is this happening.

**Comment by sunshinejr** [comment] 2019-10-01 13:43
I created a Combine support mega-thread (#1928) - closing this one.

**Closed by sunshinejr** 2019-10-01 13:43 UTC

**Comment by baazviru** [comment] 2020-09-09 13:16
please delete pod Alamofire and install pod 'Alamofire', '~> 4.7' 
100 % works for me i try creating new project i got the same issue in io 12.4.8 and 12.4.5 but when i removed pod Alamofire 
and install again pod 'Alamofire', '~> 4.7' now its working in every ios version
