### ISSUE TITLE
Stubbed responses still call the network.

### ISSUE THREAD

**Issue by crenwick** [Moya/Moya#350] opened 2015-12-17 16:57 UTC
When I stub a provider, like
```swift
let SomeProvider = MoyaProvider<SomeAPI>(stubClosure: MoyaProvider.ImmediatelyStub)
```
the code in my app is stubbed fine, however it still calls the API. 

Is there an easy and clear way to not have stubbed responses make any network calls? 

These are typically backends that I'm building simultaneously with the app, so these stubbed calls are now creating unwanted data on my endpoint or creating strange glitches for endpoints that are still under development.

Apologies if this has already been addressed -- I just couldn't find a clear answer in the issues or docs.

**Comment by wangshengjia** [comment] 2015-12-17 17:09
Before all, there is nothing to apology, and thank you for addressing this issue :100: 

The problem is probably from [here](https://github.com/Moya/Moya/blob/master/Source/Moya.swift#L220), `manager.request(urlRequest)` will call `resume()` immediately.

In my opinion, this is a bug and should be fixed. I'll look forward and propose a PR to fix this.

**Comment by swizzlr** [comment] 2015-12-18 19:20
That's unusual! And also bad! That shouldn't happen! A PR to fix this would be most welcomed. Hopefully there's a way to retrieve the AF request object without side-effecting.

**Comment by ashfurrow** [comment] 2016-01-02 16:15
I've opened an issue on Alamofire to get this sorted out. We'll see how it goes.

The problem appears to be how we structure the authentication plugins. Maybe we need to rethink the plugin architecture. Actually calling the network while stubbing seems like a serious issue and we should prioritize.

**Comment by ashfurrow** [comment] 2016-01-04 16:05
@cnoon has provided valuable feedback: https://github.com/Alamofire/Alamofire/issues/986 I believe we should follow their advice and use a custom manager instead of the shared one (while still allowing devs to pass in their own manager if they want). 

Thoughts? Feels?

**Comment by wangshengjia** [comment] 2016-01-04 16:26
Hmm, solution is surprisingly simple😂 ... but it do solve our issue.  It's OK for me. I'll update PR #354 if there is no objection.

**Comment by ashfurrow** [comment] 2016-01-04 16:28
Sounds good, thanks! In the AF issue, they had some guidelines about how to create a manager with good defaults. 

We also need to update our documentation to make it clear that we don't use the shared manager anymore. Since this is a breaking change, the next Moya version will be 6.0.0.

**Comment by wangshengjia** [comment] 2016-01-04 16:47
Yeah, in short terms, I think it would be suffice to modify ade1589 with default configuration:
```swift
    public final class func DefaultAlamofireManager() -> Manager {
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = Alamofire.Manager.defaultHTTPHeaders

        let manager = Alamofire.Manager(configuration: configuration)
        manager.startRequestsImmediately = false
        return manager
    }
```

**Comment by ashfurrow** [comment] 2016-01-04 17:04
Yup! I would add a comment pointing to the issue, too, in case someone is curious.

**Comment by ashfurrow** [comment] 2016-07-16 00:38
Looks like this is fixed in the current master: https://github.com/Moya/Moya/blob/d2897a91ee3b92214fd6e8d7636cec96a019f2dd/Source/Moya.swift#L306-L314 Going to close, thanks again for opening and the discussion!

**Closed by ashfurrow** 2016-07-16 00:38 UTC
Labels: confirmed bug
