### ISSUE TITLE
Carthage build fail

### ISSUE THREAD

**Issue by swipertharuler** [Moya/Moya#445] opened 2016-03-24 15:21 UTC
After updating to Xcode 7.3 (7D175) I get these errors when running carthage update, I'm also using Carthage 0.15.2, I also tried changing xcode-select to another Xcode of 7.2.1 without any success..

`/Users/xx/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Plugins/NetworkActivityPlugin.swift:2:8: error: module file was created by an older version of the compiler; rebuild 'Result' and try again: /Users/xx/Documents/Projekt/app/Carthage/Checkouts/Moya/Carthage/Build/iOS/Result.framework/Modules/Result.swiftmodule/arm64.swiftmodule`

`The following build commands failed:
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Moya+Alamofire.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Error.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Image.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Plugins/NetworkActivityPlugin.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Response.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Endpoint.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Plugins/CredentialsPlugin.swift
	CompileSwift normal arm64 /Users/x/Documents/Projekt/app/Carthage/Checkouts/Moya/Source/Plugins/NetworkLoggerPlugin.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)`

Hopefully someone of you guys might have an idea why this happens.. :)

**Comment by Dschee** [comment] 2016-03-25 01:27
I suggest you try removing the entire `Carthage/build` folder and run `carthage update --platform ios --no-use-binaries`. That should work, I guess.

Carthage tries by default to reuse an already built framework (like here `Result`) or even download a pre-built binary (if available) as long as the specified version didn't change. You can force Carthage to rebuild by removing the build folder and additionally ensure it doesn't download pre-built binaries by setting `--no-use-binaries`. Also I've added `--platform ios` as this saves time by not building possibly existing `tvos`, `osx` and `watchos` targets.

**Comment by jakemarsh** [comment] 2016-03-25 22:45
@Dschee I have the exact same problem and tried your suggestion and unfortunately ended up with the same error.

**Comment by ashfurrow** [comment] 2016-03-25 23:06
This is a pretty serious issue, but I don't have sufficient Carthage experience to fix it. @Moya/contributors anyone have suggestions?

**Comment by justinmakaila** [comment] 2016-03-25 23:08
'carthage update --platform iOS --no-use-binaries'

**Comment by jakemarsh** [comment] 2016-03-25 23:30
Huge thanks @justinmakaila and company, here's what finally got me fixed up on this one:

- Cleared `DerivedData`
- Deleted Carthage's `build` and `checkouts` folders
- Deleted `Cartfile.resolved`
- Ran `'carthage update --platform iOS --no-use-binaries`

I'm sure only part of that is required to fix the issue, (probably that last `--no-use-binaries` option was the _real_ fix, but building all of this takes forever so I wanted to be on a _completely_ clean state just in case.

I too am still somewhat of a Carthage novice, but my best guess is the release binary it was downloading (by default) for one of Moya's dependencies was incompatible, so specifying  `--no-use-binaries` and re-building _everything_ from source fixed it up. Just a guess though.

**Comment by justinmakaila** [comment] 2016-03-25 23:32
That's exactly what the problem is. Haha

Justin Makaila

Sent from
https://polymail.io/

On Fri, Mar 25, 2016 at 19:30 Jake Marsh

<
mailto:Jake Marsh <notifications@github.com>
> wrote:

Huge thanks
https://github.com/justinmakaila
and company, here's what finally got me fixed up on this one:

Cleared

DerivedData

Deleted Carthage's

build

and

checkouts

folders

Deleted

Cartfile.resolved

Ran

'carthage update --platform iOS --no-use-binaries

I'm sure only part of that is required to fix the issue, (probably that last

--no-use-binaries

option was the

real

fix, but building all of this takes forever so I wanted to be on a

completely

clean state just in case.

I too am still somewhat of a Carthage novice, but my best guess is the release binary it was downloading (by default) for one of Moya's dependencies was incompatible, so specifying

--no-use-binaries

and re-building

everything

from source fixed it up. Just a guess though.

**Comment by justinmakaila** [comment] 2016-03-26 00:05
@jakemarsh I'm going to go ahead and close the issue. Feel free to reopen if this doesn't seem to work!

**Closed by justinmakaila** 2016-03-26 00:05 UTC
