### ISSUE TITLE
Update ReactiveSwift dependency to 3.0

### ISSUE THREAD

**Issue by larryonoff** [Moya/Moya#1469] opened 2017-11-17 18:21 UTC
The latest Moya 10.0 version requires ReactiveSwift 2.0.

**Comment by SD10** [comment] 2017-11-17 18:29
This is a duplicate of #1468 but thank you @larryonoff

**Closed by SD10** 2017-11-17 18:29 UTC
Labels: duplicate

**Comment by larryonoff** [comment] 2017-11-17 19:17
Sorry! Someone was quicker than I.
