### ISSUE TITLE
AccessTokenPlugin's "prepare" seems to ignore MultiTarget targets

### ISSUE THREAD

**Issue by phi161** [Moya/Moya#1720] opened 2018-09-03 10:47 UTC
:sparkles: Using Moya 11.0.2 (and the Rx extensions).

I was trying to use the `AccessTokenPlugin` with a "multi-target" provider like this:

```
let provider = MoyaProvider<MultiTarget>(plugins: [
    AccessTokenPlugin(tokenClosure: "jwt_token"),
    NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)
    ])
```

and realized that authentication wouldn't work properly. After some digging, it seems that the reason is [`AccessTokenPlugin`'s `prepare`](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/AccessTokenPlugin.swift#L62) where the required target is wrapped within MultiTarget's [embedded target](https://github.com/Moya/Moya/blob/master/Sources/Moya/MultiTarget.swift#L6), so that the `as? AccessTokenAuthorizable` check will always fail.

One way to solve this would be to change [the way plugins modify requests](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider%2BInternal.swift#L67) - something like this:

```
// Allow plugins to modify request
let preparedRequest: URLRequest
if let multi = target as? MultiTarget {
    preparedRequest = self.plugins.reduce(request) { $1.prepare($0, target: multi.target) }
} else {
    preparedRequest = self.plugins.reduce(request) { $1.prepare($0, target: target) }
}
```

..but this is not very elegant :)

Anyway, is this an issue or am I somehow misusing MultiTarget?

Thanks!

**Comment by SD10** [comment] 2018-09-03 15:17
@phi161 This is a good question. I’m not sure if Moya should dig into the underlying target type or only concern itself with the top level MultiTarget. Can you make `MultiTarget` conform to `AccessTokenAuthorizable` to solve your issue? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment] 2018-09-03 17:48
@phi161  Have you confirmed that this would be a valid solution?

> One way to solve this would be to change the way plugins modify requests - something like this:
```swift
// Allow plugins to modify request
let preparedRequest: URLRequest
if let multi = target as? MultiTarget {
    preparedRequest = self.plugins.reduce(request) { $1.prepare($0, target: multi.target) }
} else {
    preparedRequest = self.plugins.reduce(request) { $1.prepare($0, target: target) }
}
```

I suspect this solution does not work as you intend, however, I have not confirmed it myself. Currently, the `target` parameter is typed as `Target` -- the generic component of a `MoyaProvider`. I believe this is what allows the compiler to know that this generic type conforms to `AccessTokenAuthorizable`. 

When you access the `multi.target` property, the return type is just a plain `TargetType` -- so I don't think the compiler will know that this type also conforms to `AccessTokenAuthorizable`. 

### How could we solve this?

We could cast to `AccessTokenAuthorizable` to check this, but this is a slippery slope in my opinion because I think it is best to keep logic relating to a specific plugin outside of Moya's internals.

### Other concerns

This also raises the question: 

**Which `TargetType` takes precedence? The `MultiTarget` or the embedded `Target`?**

In my opinion, the `MultiTarget` should be the type considered when applying any plugins because it can then be used to share plugins among the embedded targets.

Because of this, in my opinion, this is expected behavior

Also related #1492

**Comment by phi161** [comment] 2018-09-04 14:39
Thank you for your reply!

Actually the code I posted above does work since in my case `multi.target` is of type `AuthenticationTarget` which looks like this:

```
enum AuthenticationTarget {
    case login(request: LoginRequest)
    case user
}

extension AuthenticationTarget: TargetType, AccessTokenAuthorizable {
    //
}
```

meaning that [this check](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/AccessTokenPlugin.swift#L62) will be fine:

```
guard let authorizable = target as? AccessTokenAuthorizable else { return request }
```

However I did follow your recommendation and now I'm doing something like this:

```
extension MultiTarget: AccessTokenAuthorizable {
    public var authorizationType: AuthorizationType {
        switch self {
        case .target(AuthenticationTarget.user):
            return .bearer
        default:
            return .none
        }
    }
}
```

which also works fine.

Feel free to close this issue, unless you want to discuss it further and modify something else.

Thanks!

**Comment by SD10** [comment] 2018-09-11 01:11
@phi161 I'm glad you were able to resolve this 👍 I'm going to close this issue but feel free to re-open it if the problem continues

**Closed by SD10** 2018-09-11 01:11 UTC
Labels: question
