### ISSUE TITLE
pod install Error

### ISSUE THREAD

**Issue by UNIQUEXJ** [Moya/Moya#1768] opened 2018-11-19 01:36 UTC
[!] The platform of the target `Mine` (iOS 10.1) is not compatible with `Moya/RxSwift (12.0.0)`, which does not support `ios`.

**Comment by SD10** [comment] 2018-11-19 02:45
Can you share your podfile @UNIQUEXJ? I'll try some example projects with Moya now 😕

**Comment by zgjff** [comment] 2018-11-19 02:50
platform :ios, '10.0'

target '' do
  use_frameworks!

#pod 'Moya/ReactiveSwift'


I also encountered this problem.

**Comment by SD10** [comment] 2018-11-19 02:53
Thanks @zgjff I can reproduce so I'm looking into it

**Comment by Limon-O-O** [comment] 2018-11-19 03:03
The platform of the target `Example` (iOS 10.0) is not compatible with `Moya/RxSwift (12.0.0)`, which does not support `ios`.

**Comment by SD10** [comment] 2018-11-19 03:32
Could be related to #1758 and #1766 but I'm still unsure. The deployment targets are set for the RxSwift and ReactiveSwift targets in the xcodeproj. All platforms are supported for the targets in build settings as well

**Comment by SD10** [comment] 2018-11-19 03:42
@Moya/core-team Anyone has any ideas as to what's wrong here?

**Comment by SD10** [comment] 2018-11-19 04:04
Yeah, so it looks like it's related to defining the `ss.watchos.deployment_target` inside of the subspecs is the culprit. I don't know if we can have different deployment target for different subspecs. 

The previous minimum deployment target is 2.0 and RxMoya now requires 3.0. The best solution might be to just make the minimum deployment target 3.0 overall

**Comment by UNIQUEXJ** [comment] 2018-11-19 05:40
> [!] The platform of the target `Mine` (iOS 10.1) is not compatible with `Moya/RxSwift (12.0.0)`, which does not support `ios`.

platform :ios, '10.1'
use_frameworks!
target 'SwiftProject' do 
  pod 'Moya/RxSwift'
end

**Comment by SD10** [comment] 2018-11-19 06:19
Reopening because this is still broken when downloading from CocoaPods. Installing locally works for me now. Don't think I can fix this tonight

**Comment by zgjff** [comment] 2018-11-19 06:37
Use this method  before fix.
pod 'Moya/ReactiveSwift', '~> 11.0.2'
pod 'ReactiveCocoa', '~> 7.0.1'

**Comment by SD10** [comment] 2018-11-19 07:02
@UNIQUEXJ @zgjff @Limon-O-O This should be fixed by Moya version 12.0.1. Can you please let me know if that works for you? Really sorry about this 😓 

I'm going to leave this open for visibility

**Comment by andre991** [comment] 2018-11-23 11:46
Moya 12 is Not working with watchos 4.3 for me. Any solutions??
![screen shot 2018-11-23 at 09 45 59](https://user-images.githubusercontent.com/8302454/48941943-a6137200-ef04-11e8-80c3-bd03331542e4.png)

**Comment by SD10** [comment] 2018-11-23 19:53
@andre991 Hey there,
1. Make sure you are using Moya version 12.0.1
2. Try deleting your derived data folder and rebuild
3. Make sure your deployment target is set to 3.0 in your project

**Comment by andre991** [comment] 2018-11-24 00:55
> @andre991 Hey there,
> 
> 1. Make sure you are using Moya version 12.0.1
> 2. Try deleting your derived data folder and rebuild
> 3. Make sure your deployment target is set to 3.0 in your project

Hi @SD10, me and @LucianoPAlmeida managed to identify the error, it is in the dependencies in the podspec of [MoyaObjectMapper](https://github.com/bmoliveira/Moya-ObjectMapper). I'll create a PR there in their github to fix this problem. Thank you.

**Comment by sunshinejr** [comment] 2019-04-11 10:29
I think this one is fixed so I'm closing it. Thanks everyone for participation!

**Closed by sunshinejr** 2019-04-11 10:29 UTC
Labels: cocoapods, confirmed bug, reactivemoya, rxmoya
