### ISSUE TITLE
Type 'X' does not conform to protocol TargetType

### ISSUE THREAD

**Issue by dropski** [Moya/Moya#511] opened 2016-06-16 20:59 UTC
There is an issue like in title above, here is my code
```
import Moya

enum UserAPIService {
  case Register(user: User!)
  case Login(login: String!, password: String!)
}

// MARK: - TargetType Protocol Implementation
extension UserAPIService: TargetType {
  var baseURL: NSURL { return APIServiceConst.baseURL! }

  var path: String {
    switch self {
    case .Register:
      return "/user/create"
    case .Login:
      return "/user/login"
    }
  }

  var method: Moya.Method {
    switch self {
    case .Register, .Login:
      return .POST
    }
  }

  var parameters: [String: AnyObject]? {
    switch self {
    case .Register(let user):
      return user.toJSON()
    case .Login(let login, let password):
      return ["login": login, "password": password]
    default:
      return nil
    }
  }

  var sampleData: NSObject {
    switch self {
    case .Register:
      return "".UTF8EncodedData
    case .Login:
      return "".UTF8EncodedData
    }
  }
}

// MARK: - Helpers
private extension String {
  var URLEscapedString: String {
    return self.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLHostAllowedCharacterSet())!
  }
  var UTF8EncodedData: NSData {
    return self.dataUsingEncoding(NSUTF8StringEncoding)!
  }
}
```

I'm using cocoapods and your latest commit 
`pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :commit => '122d2f8'`

**Comment by dropski** [comment] 2016-06-16 21:13
my bad, there should by NSData instead of NSObject, please close the issue. Sorry.

**Comment by colinta** [comment] 2016-06-16 21:18
@dropski I would humbly encourage you to close the issue, because I've seet lots of open-source projects where there are tons of issues still open, only because the maintainers can't tell if the person who opened the issue is "happy" with the results.  It's a good way to keep things tidy!

**Closed** 2016-06-16 21:20 UTC
