### ISSUE TITLE
Build error related to NSURL optionals in Swift 2.3

### ISSUE THREAD

**Issue by MacroYau** [Moya/Moya#626] opened 2016-09-14 04:04 UTC
I have recently updated to Xcode 8 and attempted to convert my existing projects to Swift 2.3. Even though I updated Moya to 7.0.1 through CocoaPods, the following build error persists from the following Moya source code (as a part of the extension of `MoyaProvider`): `Value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?`

```Swift
public final class func DefaultEndpointMapping(target: Target) -> Endpoint<Target> {
    let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
    return Endpoint(URL: url, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
}
```

Hope this can be resolved soon. Thanks very much!

**Comment by RyogaK** [comment] 2016-09-14 09:30
@ashfurrow Hi, I'm investigating this issue for also me.
There is `release-7.0.1` branch, and also there is `7.0.1` tag. However, the tag is tagged at the same commit as `7.0.0`. 
That branch is working in Swift2.3, I know. Perhaps, that tag is a mistake? if so, I want to tag `7.0.1` on `release-7.0.1` branch.

**Comment by pedrovereza** [comment] 2016-09-14 12:19
Hey, `7.0.1` is tagged at the same commit as `7.0.0`, but that's was a conscious decision
Details here: https://github.com/Moya/Moya/pull/594#issuecomment-246513882

**Comment by ashfurrow** [comment] 2016-09-14 16:59
Yup, it was caused by a mistake on my part, working to fix it and release Moya with Swift 2.3 compatibility today.

**Comment by ashfurrow** [comment] 2016-09-14 18:30
This should be fixed now, could you try updating to Moya 7.0.2 and letting us know if it works?

**Comment by dangthaison91** [comment] 2016-09-14 18:42
I still get the error. Seem that code was not update?

**Comment by BasThomas** [comment] 2016-09-14 18:46
Are you using Cocoapods or Carthage? Is the version number `7.0.2`?

**Comment by dangthaison91** [comment] 2016-09-14 20:11
@BasThomas Yes, i'm using CocoaPods and pod version is 7.0.2. Try to set to 7.0.0 but it still load as 7.0.2?

**Comment by ashfurrow** [comment] 2016-09-14 20:28
7.0.2 is what you want for Swift 2.3. Try `pod update Moya`, without specifying a version in your Podfile. That should install the latest version, which is 7.0.2. Maybe try deleting the `Pods` directory, if you can, and re-run `pod install`.

**Comment by MacroYau** [comment] 2016-09-15 03:21
@ashfurrow Looks good after updating to 7.0.2. Thanks the team for your quick response!

**Comment by dangthaison91** [comment] 2016-09-15 04:05
Oops, sorry, i'm using XCode 7.3.1/Swift 2.2. 
In #631 @ashfurrow told that 7.0.1 is latest version support Swift 2.2.. But i cannot install although i have specific version number in pod, it always get 7.0.2.

This is my pod:
`
  pod 'Moya', '~> 7.0.0'
    pod 'Moya/RxSwift', '~> 7.0.0'
    pod 'ObjectMapper'
    pod 'Moya-ObjectMapper/RxSwift', '~> 1.3.1'
`
Here is pod log:

> Installing Moya (7.0.2)
Installing Moya-ObjectMapper (1.3.1)
Installing ObjectMapper (1.4.0)

**Comment by sunshinejr** [comment] 2016-09-15 04:14
@dangthaison91 You need to explicitly specify that you want Moya 7.0.0. You can do this like:
```
    pod 'Moya', '7.0.0'
    pod 'Moya/RxSwift', '7.0.0'
```

You can check [here](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) what `~>` means and more in a Podfile. Hope it helps!

**Comment by dangthaison91** [comment] 2016-09-15 04:34
Thanks @sunshinejr, i used wrong opertor :(. Thanks the team for yours really quick response!

**Closed** 2016-09-15 04:34 UTC
Labels: bug?
