### ISSUE TITLE
Moya Can not support  IOS 8?

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#786] opened 2016-11-21 09:26 UTC
![631c073a-5872-44a2-9ea4-c5532f8c56ae](https://cloud.githubusercontent.com/assets/8953791/20477253/bc3ff796-b00f-11e6-8b8e-ac24f5337b92.png)
how solve it ?

**Comment by zhaoyunyi** [comment] 2016-11-21 09:33
#782 I get it , i hope soon ,thanks

**Comment by sunshinejr** [comment] 2016-11-21 10:09
Yeah, I will close this one as this is a duplicate of #782, let's track the process there. 👊

**Closed by sunshinejr** 2016-11-21 10:09 UTC
