### ISSUE TITLE
Undefined behavior when using both endpointClosure and plugins

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1549] opened 2018-01-19 06:52 UTC
After reviewing issue #1546, it made me conscious of where we reference `Endpoint` or `TargetType` in Moya's internals to retrieve information to form a request.

This led me to discover some potentially undefined behavior when modifying an `Endpoint` through an `endpointClosure` and using a `PluginType` with a `MoyaProvider`. May be related to #1448 

If you modify an `Endpoint` through the `endpointClosure`, ie) add headers, these headers will not be available to the `PluginType` when it calls its delegate methods. This is because plugins are passed the original `TargetType`. 

There would be inconsistencies with any information that `TargetType` and `Endpoint` share.

I'm not sure what we can do to resolve this, but at the very least I would like to document it. 

I did write a small unit test for this yesterday 😅 @Moya/contributors Please let me know if I am wrong

**Comment by ashfurrow** [comment] 2018-01-19 15:40
Hmm, interesting. Is the unit test in #1550?

**Comment by sunshinejr** [comment] 2018-01-19 15:52
@ashfurrow these two cases are separate, in #1550 there is a fix for a bug that if you appended multipart data in `endpointClosure`, the request wouldn't respect it and wouldn't add it to the list.

For this case though, I don't think there is a specific problem. Let me explain: `endpointClosure` is in fact a way of transitioning from the `target` to the `endpoint`. Every plugin's method receive `target` as a way of telling which `target` did something and we can react. These plugins do not receive `endpoint`, which is gathered after using `endpointClosure` on a target. In fact, you could get an endpoint when manually executing `endpointClosure` on given `target` that is passed through.

Let me know if it makes sense.

**Comment by SD10** [comment] 2018-01-19 16:15
The easiest way to see it is:
1. Modify an Endpoint’s task through an `endpointClosure`.

2. Add a `PluginType` with a `prepare(request:target)` method to Moya provider.

3. The task of `TargetType` passed into `prepare(request:target)` won’t have the changes from the endpoint closure. 

Probably not a huge issue. The behavior actually makes sense because plugin delegate methods are handed the original target and not an `Endpoint`. Maybe just good to document?



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashfurrow** [comment] 2018-01-19 16:29
Okay, that makes sense! I wonder if we could add `assert`s to alert developers if they are hitting this edge case? Make it fail loudly when developing, but silently when in production?

For these types of discussions around nuanced behaviour, sometimes a PR demonstrating the unexpected behaviour in a unit test can help explain the background. For community members who either haven't worked in plugin code yet or (like me) have forgotten how plugins work altogether :wink: To be clear, this issue is very well laid-out and explained the problem very well (well done @SD10, and well-spotted). Just wanted to mention a useful tool to keep in your toolbox.

**Comment by sunshinejr** [comment] 2018-01-19 16:36
> 3. The task of `TargetType` passed into `prepare(request:target)` won’t have the changes from the endpoint closure.

It won't because `endpointClosure` doesn't change/update `TargetType`, it creates a completely new object that is of an `Endpoint` type (and while it most of the time bases on `TargetType`, sometimes it doesn't at all). We could document it but right now I'm not sure where/how.

Also, I agree that `plugins` in its current state overlap some of the closures(both `endpoint`, `request`) functionalities, that's why I've tried to unify them into one unit in #1123, maybe we should try to revisit sometime in the future.

**Comment by SD10** [comment] 2018-01-19 16:56
@ashfurrow I should’ve made some sort of PR or example demonstration for sure. I was on the fence about opening this issue. As for asserts, there’s little we can do IMO. We would have to check all the properties that Endpoint and TargetType share to check for inconsistencies. It’s not worth having those checks on every request as this is an edge case.

To be honest, I’m not ashamed to admit I think this is a pretty nitty issue after a good nights sleep.

> It won't because `endpointClosure` doesn't change/update `TargetType`, it creates a completely new object that is of an `Endpoint` type (and while it most of the time bases on `TargetType`, sometimes it doesn't at all). We could document it but right now I'm not sure where/how.

Perfectly worded 👍


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment] 2018-01-19 17:02
@sunshinejr I agree with your quote from #1123 

> Right now plugins: 

> - Do many things that endpointClosure & requestClosure do as well - making it ambiguous for users to use & for us to recommend a good practice.

In fact, I'd argue that is the crux of this issue. You can achieve the same thing two different ways and if you use a little bit of both - something unexpected might happen.

But Moya could be a little too mature to remove the `endpointClosure` & `requestClosure`. I can only imagine how much logic people have there.

**Comment by sunshinejr** [comment] 2018-01-21 21:51
I agree that all the closures are a core of Moya right now. Although, we might think about a smooth migration process and maybe a deprecation when Swift 5 comes? Then we have some time to focus on this one and think about all pros and cons.

**Comment by SD10** [comment] 2018-01-21 22:02
The closures + plugins are capable of the same things, with one exception. The `endpointClosure` is the access point for modifying the `EndpointSampleResponse`. However, #1502 would remove this responsibility and make it customizable through a new `TestTargetType` protocol. This would allow `EndpointSampleResponse` to be modified through either `TestTargetType` directly or inside plugins with a simple cast. Which is pretty cool IMO, **you could create plugins solely for testing**. 

Nevertheless, I wouldn't take #1502 or removing the closures lightly.

**Comment by sunshinejr** [comment] 2018-01-27 19:21
Closing this one as I think we've reached an agreement on the issue 😄 We can expand on plugins in other issues 👍

**Closed by sunshinejr** 2018-01-27 19:21 UTC
Labels: discussion
