### ISSUE TITLE
modile complied with swift 4.0 cannot be imported in swift 3.1

### ISSUE THREAD

**Issue by wz1383691** [Moya/Moya#1187] opened 2017-07-24 03:18 UTC
moya->core->AccessTokenPlugin.swift
import Result
error:modile complied with swift 4.0 cannot be imported in swift 3.0 :myPath

**Comment by sunshinejr** [comment] 2017-07-27 14:52
Duplicate of #1189.

**Comment by wz1383691** [comment] 2017-07-28 06:21
thank you

**Closed** 2017-08-09 22:16 UTC
Labels: question
