### ISSUE TITLE
Add Moya.Response extension for Decodable types in Swift 4

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1118] opened 2017-06-12 06:29 UTC
It seems like handling response JSON is a highly debated topic due to there being so many JSON serialization libraries and no determined best practice. 

However, with the addition of the `Codable` protocol to the Swift 4 Standard Library, I think this will become a widely used approach. I'm wondering if the Moya community would be willing to add some basic extensions to `Moya.Response` to map `Decodable` types. 

Since `Codable` is part of the Standard Library I think it's a safe addition to Moya's core.

A rough API would be:

```Swift
    func mapObject<D: Decodable>(with decoder: JSONDecoder) throws -> D {}
    func mapObject<D: Decodable>(atKeyPath keyPath: String, with decoder: JSONDecoder) throws -> D {}
```

Moya already supports mapping to JSON, Images, and Strings

Regardless, these are not difficult extensions to write on our own or provide in a community extension.

**Comment by BasThomas** [comment] 2017-06-12 06:45
Hmm, this is an interesting one. Not sure what to think of it yet.

**Comment by sunshinejr** [comment] 2017-06-12 18:52
Thanks for the issue, @SD10 - this is a really good idea. Having standardized encoding/decoding by Swift standard library, I think it is natural for us to implement a basic map method that would cover this behavior. However, for now we don't have any Swift 4.0 branch and we are in the middle of Moya 9.0 release, so we might want to wait with that implementation.

**Comment by SD10** [comment] 2017-06-12 20:33
@sunshinejr thank you for the feedback. I would be willing to provide the implementation for this feature when Moya is ready to start the Swift 4 migration. Including writing the Rx/Reactive extensions, documentation, and testing. If there's anything else I can do the contribute in the meantime, please feel free to let me know.

**Comment by AndrewSB** [comment] 2017-06-13 01:17
Thanks for taking the initiative @SD10! That sounds great, we'll update this issue once we cut a 9.0 release 😄

**Comment by Dschee** [comment] 2017-06-27 03:47
Please note that there is now https://github.com/Alamofire/Alamofire/issues/2180 around which tracks support for the `Decodable` type right within Alamofire. As it is our main dependency, I think their approach to integrate this feature should be considered before finally deciding on how to implement this. Please note that the contributors have already confirmed that they have plans to support both `Encodable` and `Decodable` types in release version 5 in https://github.com/Alamofire/Alamofire/issues/2177.

**Comment by SD10** [comment] 2017-09-24 19:03
@devxoul You may be interested in working on this one? I just saw [RxCodable](https://github.com/devxoul/RxCodable).

I have a branch that's part way through on my local copy but I thought I'd get your thoughts. Not trying to dictate contributions, just thought you may be interested 😃

**Comment by devxoul** [comment] 2017-09-25 18:09
@SD10 It looks interesting. I think I can do it :)

**Comment by sunshinejr** [comment] 2017-09-27 22:28
Hey @devxoul, just making sure - do you think you will want to implement this one? If not we might want to add labels to seek for help 😉

**Comment by devxoul** [comment] 2017-09-28 05:45
@sunshinejr, oh yeah I'm currently working on it. I'll make a pull request in this week :)

**Comment by sunshinejr** [comment] 2017-09-28 06:41
That's great! I assigned you to this task then 😉

**Comment by devxoul** [comment] 2017-10-01 12:56
#1335 :tada:

**Comment by SD10** [comment] 2017-10-01 19:48
Closing this in favor of #1335. Let's move the discussion there 🎉

**Comment by BasThomas** [comment] 2017-10-01 20:13
Why do we close these issues if they get auto-closed after the PR is merged? Now, if for some reason the PR isn't merged, there's a big chance this issue gets overlooked and stays closed.

**Comment by SD10** [comment] 2017-10-01 20:19
Good point @BasThomas. I always thought it was to encourage discussion on the PR and not have it split across two places. Feel free to reopen this and maybe we can default to the policy you described

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment] 2017-10-01 20:24
I can't remember this happening somewhere actually, and I feel like the auto-closing works best. But if I am in a minority here, I'd not want to change the way this is handled now. @Moya/contributors, what do you think?

**Comment by devxoul** [comment] 2017-10-02 07:21
I think we should keep this issue open because there could be another pull request in different idea. Also this is will be automatically closed if #1335 is merged.

**Comment by BasThomas** [comment] 2017-10-12 11:52
We can close this now :)

**Closed by BasThomas** 2017-10-12 11:52 UTC
Labels: enhancement, question

**Comment by devxoul** [comment] 2017-10-12 11:57
Hmm I have no idea why GitHub didn't close this issue automatically when #1335 is merged 🤔

**Comment by BasThomas** [comment] 2017-10-12 11:58
Think it was confused because we closed an reopened manually 😛

**Comment by devxoul** [comment] 2017-10-12 12:05
Ah, that makes sense!
