### ISSUE TITLE
Dependency injection by incident

### ISSUE THREAD

**Issue by onmyway133** [Moya/Moya#233] opened 2015-09-24 15:13 UTC
Regard the demo in this repo about GithubProvider

```
public enum GitHub {
    case Zen
    case UserProfile(String)
    case UserRepositories(String)
}

extension GitHub : MoyaTarget {
...
}
```

Normally, we would pass the MoyaTarget instance to the MoyaProvider (the enum Github in this case, but it could be struct, class, whichever conforms to MoyaTarget), like this
```
let GitHubProvider = MoyaProvider(Github.Zen)
```

but the way you use generic,
```
let GitHubProvider = MoyaProvider<Github>()
```

I find this interesting because we can leverage generic and still can call methods on the `MoyaTarget`, without passing the instance into `MoyaProvider`

**Comment by petester42** [comment] 2015-09-24 15:19
The `MoyaTarget` never gets passed the the provider directly. You call `provider.request(Github.Zen)`. Could you elaborate on what the issue is?

**Comment by ashfurrow** [comment] 2015-09-24 15:20
Well, it gets passed in to the Initializer – the `MoyaProvider` is a generic type _on_ `MoyaTarget`, so it needs to know what the type is. I'm not sure if `MoyaProvider(GitHub.Zen)` would work, but I haven't tried it. There's no initializer that it could call – or is this a Swift thing I'm not aware of?

**Comment by onmyway133** [comment] 2015-09-24 16:24
@petester42 @ashfurrow this is not an issue. Maybe I misunderstand the code

**Comment by ashfurrow** [comment] 2015-09-24 16:27
@onmyway133 issues are for questions and clarifications, too! I want to make sure that we're on the same page. Let's start over:

What is happening that you don't expect? What is _not_ happening that you _do_ expect?

**Comment by onmyway133** [comment] 2015-09-25 02:44
I just misunderstood the code. Now I'm realize that `MoyaProvider` uses generic on `MoyaTarget`, and indeed, `MoyaTarget` instance is passed into `MoyaProvider` 's request method

**Comment by ashfurrow** [comment] 2015-09-25 12:04
Yup! And you can only pass enum values of the correct type to the request method, since they're compile-time checked 🎉

**Comment by orta** [comment] 2015-10-08 13:08
Closing, as I think this is sorted :+1:

**Closed by orta** 2015-10-08 13:08 UTC
