### ISSUE TITLE
Objects with RxMoyaProvider are no longer retained in 9.0

### ISSUE THREAD

**Issue by bhstrifork** [Moya/Moya#1267] opened 2017-09-06 13:49 UTC
Hey,

I'm running into an interesting issue with Moya 9.0

I have a `Service` type for each kind of request that looks like:

```swift
struct UserService {
    let provider: MoyaProvider<MyAPI>
    
    init(provider: MoyaProvider<MyAPI>) {
        self.provider = provider
    }

    func login(usingUsername username: String, password: String) -> Single<String?> {
        return self.provider.rx.request(.login(username: username, password: password))
            .performMapping()
    }
}
```

This is then used like this from a singleton class:

```swift
let userService = UserService(provider: MoyaProvider<MyAPI>())
userService.performLogin(username: "foo", password: "bar").subscribe(onSuccess: {...}, onError: {...}
```

This used to work fine in Moya 8.x, where I was using a `RxMoyaProvider`. Any suggestions to workarounds or whether this should be fixed on Moya's side?

**Comment by bhstrifork** [comment] 2017-09-06 13:54
Forgot to add usage example of the service.

**Comment by pedrovereza** [comment] 2017-09-06 14:57
@bhstrifork Hey, could you clarify which behavior is different now? I can get a hint from the issue title, but I feel a more complete description would be helpful :wink:

**Comment by bhstrifork** [comment] 2017-09-06 15:03
Yeah, I should've been clearer.

In Moya 8.x I could use the `UserService` as shown above, and it would not get deallocated. Now in Moya 9.0 it is deallocated immediately, meaning my request either doesn't fire, or I never receive the response in my subscription. I was trying to find the issue discussing this already in Moya 8, but I can't seem to find it.

So basically I would like to have a function call as follows:

```swift
func login() {
  let userService = UserService(provider: MoyaProvider<MyAPI>())
  userService.performLogin(username: "foo", password: "bar")
    .subscribe(onSuccess: {...}, onError: {...}
}
```

And then maybe have it call a completion or similar. Or even just forward the request like this:

```swift
func login() -> Single<String?> {
  let userService = UserService(provider: MoyaProvider<MyAPI>())
  return userService.performLogin(username: "foo", password: "bar")
}
```

So the caller doesn't have to care about the `UserService`.

Does this clarify things?

**Comment by AndrewSB** [comment] 2017-09-06 22:00
I think the issue is the provider itself isn't retained, usually a singleton is defined somewhere outside with a `static let`. Are you familiar with how ARC works in Swift?

Here is your function with some annotations from me
```swift
func login() {
  // begin creating a UserService
  //      create a MoyaProvider to pass in as a param
  //      set the UserService.provider to this MoyaProvider (in UserService.init)
  let userService = UserService(provider: MoyaProvider<MyAPI>())
   
  // create an Observable - nothing interesting here
  userService.performLogin(username: "foo", password: "bar")
    .subscribe(onSuccess: {...}, onError: {...}

  // we're about to leave the scope of this function! free any local variables we created!
  //   userService has 0 strong references and will be disposed of
  //      all of userService's instance variables (userService.provider included) will all be disposed of as well if they have 0 references -- which in this simple case they do
}
```

**Comment by bhstrifork** [comment] 2017-09-07 05:26
So, I was thinking about this last night and I realized that I actually don't keep a reference to the provider as stated is required in the docs. Like you also point out. I am familiar with ARC though. I guess a way to simplify the example is to simply remove `UserService` from the equation.

Moya 8.x let's me do the following:

```swift
func login() -> Observable<String?> {
  let provider = RxMoyaProvider<MyAPI>()
  return provider.request(.login(username: username, password: password))
            .performMapping()
}
```

It could be that this is a bug in Moya 8.x, but I do recall an issue talking about this being a use case.

**Comment by bjarkehs** [comment] 2017-09-07 05:30
Anyway, I think this is non-obvious behaviour anyway. So I'll find a way to work around it on my end.

**Comment by bhstrifork** [comment] 2017-09-07 05:32
Anyway, I think this is non-obvious behaviour anyway. So I'll find a way to work around it on my end.

**Comment by AndrewSB** [comment] 2017-09-07 15:08
@bhstrifork that does look like a pretty serious bug in 8.x, are you sure that request's subscription fired? Can you give me a commit hash of Moya where you were able to repro, or exactly which version?

If you think it's non obvious behaviour we should re-examine our code and see if there's anyway to make it easier to reason about -- if you're interested, I'd be more than happy to make changes based on what you think is wrong; can you explain what doesn't make sense?

**Comment by bjarkehs** [comment] 2017-10-11 17:20
Just realized I made this from the wrong account. Oh well.

Sorry about the _very_ slow response. The commit hash is: `4512a2a4bc8019cf006434378ac6a0640f34f35f`

It seems that @volodg is also relying on this behaviour in Moya 8.x from how I interpret their response in https://github.com/Moya/Moya/pull/1294#issuecomment-331320987

I think this was a, potentially unintended, behaviour that people ended up relying on. I do think that the new behaviour is easier to reason about, and you don't end up with potential reference cycles as easily.

I think this issue can just be closed.

**Comment by AndrewSB** [comment] 2017-10-12 00:26
Hmm, it looks like maybe the bug was fixed in https://github.com/Moya/Moya/blob/master/Changelog.md#900-alpha1

That makes sense, thanks for reporting @bjarkehs

**Closed by AndrewSB** 2017-10-12 00:26 UTC
Labels: question
